import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const satoshi = localFont({
  src: ".././fonts/Satoshi-variable.ttf",
  display: "swap",
  variable: "--font-satoshi",
  style: "normal",
});

// const satoshiItalic = localFont({
//   src: ".././fonts/Satoshi-VariableItalic.ttf",
//   display: "swap",
//   variable: "--font-satoshi-italic",
//   style: "italic",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col ${satoshi.className}`}>{children}</body>
    </html>
  );
}
